### ISSUE TITLE
Typographic quotes from iOS are not being parsed

### ISSUE THREAD

**Issue by TheFiZi** [kittenswolf/aid-issues#1]
Appears iOS formats it's quotes differently than the Desktop Apps and the bot is not able to parse them:

![image](https://user-images.githubusercontent.com/1762426/74612265-94ddf480-50b8-11ea-80f3-71b89731e558.png)

The difference is subtle but the iOS quotes have more for an angle to them. Reminds me of that terrible Microsoft Office feature called "Smart quotes"

I do not have access to an Android device to check if this is an issue on that platform as well.

On iOS I can copy/paste someone else's message written from a desktop client, remove their content but leave the quotes and have the bot parse the message properly.

Edit: [I just learned way more than I care to know about quotation marks...](https://en.wikipedia.org/wiki/Quotation_marks_in_English)

**Comment by TheFiZi** [comment]
Assuming Github doesn't alter the characters, here are the actual quotes from iOS compared to a desktop client

`“What do you think we’ll find?”` <- iOS

`"What do you think we'll find?"` <- Desktop Client

**Comment by TheFiZi** [comment]
Friend suggested I provide a UUID for a sample of the iOS quotes as well: 678700032421003284

**Comment by TheFiZi** [comment]
This issue does not appear to affect Android

**Comment by kittenswolf** [comment]
Fixed, thank you!
